version: '3' 
services:
  web:
    build: .    
    image: python_docker:2.0.0
    command: python -u main.py
    ports:
      - "80:80"
    volumes:
      - .:/app
    links:
      - db
  db:
    image: mongo:3.0.2
    ports:
      - "27018:27017"