version: '3' 
volumes:
  mongodata:
    external:
      name: "mongodata"

services:
  web:
    build: .    
    image: python_docker:3
    command: python -u main.py
    ports:
      - "80:80"
    volumes:
      - .:/app
    links:
      - db
    depends_on:
      - 'db'
  db:
    image: mongo:4.0
    # command: mongod
    # restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongodata:/data/db